
clean:
	rm -rf day1/pass1/_work day1/pass1/*.h5 day1/pass2/_work day1/pass2/*.h5
	rm -rf day2/pass1/_work day2/pass1/*.h5 day2/pass2/_work day2/pass2/*.h5
	rm -rf days_1_2/pass1/_work days_1_2/pass1/*.h5 days_1_2/pass2/_work days_1_2/pass2/*.h5

